zn "%SYS"

do ##class(%SYSTEM.License).Upgrade()
do ##class(SYS.Container).QuiesceForBundling()
do ##class(Security.Users).UnExpireUserPasswords("*")
set sc=##class(%SYSTEM.OBJ).Load("/opt/irisapp/DemoSetup.Utilities.cls","ck")
set helper=##class(DemoSetup.Utilities).%New()
do helper.EnableSSLSuperServer()
do ##class(Security.Applications).Import("/ApplicationInquisidor.xml",.n)

zn "INQUISIDOR"
set sc = $SYSTEM.OBJ.LoadDir("/opt/irisapp/src/Inquisidor", "ck", , 1)
do ##class(%SYSTEM.SQL.Schema).ImportDDL("/init.sql","/iris-shared/logfile.log","IRIS")
set production = "Inquisidor.Production"
set ^Ens.Configuration("csp","LastProduction") = production
do ##class(Ens.Director).SetAutoStart(production)